# Generated by Django 5.2 on 2025-05-12 07:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table_comment': 'Stores tags used to label news articles.',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('source', models.URLField(max_length=256)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='news', to='news.tags')),
            ],
            options={
                'db_table_comment': 'Table for storing news posts',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('title', 'source'), name='unique_news_per_source'), models.CheckConstraint(condition=models.Q(('status', True), ('published_at__isnull', False)), name='published_news_must_have_date')],
            },
        ),
    ]
