# Generated by Django 5.2 on 2025-05-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='news',
            name='published_news_must_have_date',
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
