# Generated by Django 5.2 on 2025-05-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_published_news_must_have_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
